version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "📦dependencies"
    assignees:
      - "fredrikj31"
    commit-message:
      prefix: "chore(pnpm): "
